# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/typoverflow"

[social.params]
icon = "brand-github"

[[social]]
identifier = "X"
name = "X"
url = "https://x.com/chenxiaogao"

[social.params]
icon = "brand-x"

[[social]]
identifier = "email"
name = "email"
url = "mailto:typoverflow@outlook.com"

[social.params]
icon = "mail"


